## Escalares en Python:

Un escalar es un número simple que puede ser real o natural.

La librería numpy en Python permite definir hasta 24 tipos de escalares. 

In [11]:
import numpy as np

#Un ejemplo de escalares y su conversión con Numpy
a = np.float16(0.1)
b = np.float32(a)
c = np.float64(b)
a,b,c

(0.1, 0.099975586, 0.0999755859375)

## Vectores en Python:

Son arreglos, sin embargo, la libería numpy tiene una función para convertir listas en arreglos (vectores horizontales)

In [12]:
import numpy as np

#Se define la lista
lista=[23,45,7]
l =np.array(lista)
l


array([23, 45,  7])

#### Operaciones sobre vectores

##### Suma, resta, multiplicación, división, producto punto y multiplicación por escalar de vectores usando numpy

In [13]:
#Se establecen las listas
l1 = [2, 3, 6, 3]
l2 = [4, 7, 22, 15]

#Se definen los vectores
v1 = np.array(l1)
v2 = np.array(l2)

#Suma de vectores
sumaV = v1 + v2
print(sumaV)

#Resta de vectores 
restaV = v1 - v2
print(restaV)

#Multiplicación de vectores
multiplicaV = v1 * v2
print(multiplicaV)

#División de vectores
divideV = v1/v2
print(divideV)

#Producto punto
productoPunto = v1.dot(v2)
print(productoPunto)

#Multiplicar por un escalar
valorEscalar = 0.7
#Multiplicación del vector 1 por el valor escalar
multiEscalarv1 = v1 * valorEscalar
print(multiEscalarv1)

[ 6 10 28 18]
[ -2  -4 -16 -12]
[  8  21 132  45]
[0.5        0.42857143 0.27272727 0.2       ]
206
[1.4 2.1 4.2 2.1]


## Matrices en Python:

Son arreglos de dos dimensiones donde cada número está identificado por 2 indicadores (fila y columna)

In [14]:
#Definir la matriz
m1 = np.matrix('2, 4, 39; 45, 7, 6')
m1

matrix([[ 2,  4, 39],
        [45,  7,  6]])

## Tensores en Python:

Los tensores son arreglos multidimensionales (N-D) en una red regular de N-ejes. Son muy importantes para aprendizaje de máquina, aprendizaje profundo y visión por computador, entre otros. 

In [16]:
#Definir un tensor

t1 = np.array([[56, 183, 1],
             [78, 178, 2],
             [50, 165, 0]])
t1.ndim, t1.shape

(2, (3, 3))